version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    environment:
      PHP_MEMORY_LIMIT: "512M"
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./../:/var/www/
    command: >
      sh -c "sleep 3 && php bin/console doctrine:migrations:migrate --no-interaction && php-fpm"
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

  db:
    image: mysql:8.0
    container_name: main_bd
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test_balancer_bd
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:

